### ISSUE TITLE
Cannot import altair Chart in python 3.14

### ISSUE THREAD

**Issue by alec-bike** [vega/altair#3879]
### What happened?

I'm testing python 3.14 with altair and get the following error:

```sh
    from altair import Chart
  File ".venv/lib/python3.14/site-packages/altair/__init__.py", line 649, in <module>
    from altair.vegalite import *
  File ".venv/lib/python3.14/site-packages/altair/vegalite/__init__.py", line 2, in <module>
    from .v5 import *
  File ".venv/lib/python3.14/site-packages/altair/vegalite/v5/__init__.py", line 2, in <module>
    from altair.expr.core import datum
  File ".venv/lib/python3.14/site-packages/altair/expr/__init__.py", line 11, in <module>
    from altair.expr.core import ConstExpression, FunctionExpression
  File ".venv/lib/python3.14/site-packages/altair/expr/core.py", line 6, in <module>
    from altair.utils import SchemaBase
  File ".venv/lib/python3.14/site-packages/altair/utils/__init__.py", line 1, in <module>
    from .core import (
    ...<9 lines>...
    )
  File ".venv/lib/python3.14/site-packages/altair/utils/core.py", line 22, in <module>
    from altair.utils.schemapi import SchemaBase, SchemaLike, Undefined
  File ".venv/lib/python3.14/site-packages/altair/utils/schemapi.py", line 29, in <module>
    from typing_extensions import TypeAlias
ModuleNotFoundError: No module named 'typing_extensions'
```

### What would you like to happen instead?

no error

### Which version of Altair are you using?

altair 5.5.0 with python 3.14-rc3

**Comment by alec-bike** [comment]
Trying again with released python 3.14. Seems like `typing_extensions` is no longer resolved as a dependency, at least when using uv. If I manually add this as a dependency, I get the following error:

```sh
Traceback (most recent call last):
  File "plot_core.py", line 3, in <module>
    from altair import Chart
  File ".venv/lib/python3.14/site-packages/altair/__init__.py", line 649, in <module>
    from altair.vegalite import *
  File ".venv/lib/python3.14/site-packages/altair/vegalite/__init__.py", line 2, in <module>
    from .v5 import *
  File ".venv/lib/python3.14/site-packages/altair/vegalite/v5/__init__.py", line 3, in <module>
    from altair.vegalite.v5 import api, compiler, schema
  File ".venv/lib/python3.14/site-packages/altair/vegalite/v5/api.py", line 19, in <module>
    from altair import theme, utils
  File ".venv/lib/python3.14/site-packages/altair/theme.py", line 9, in <module>
    from altair.vegalite.v5.schema._config import (
    ...<70 lines>...
    )
  File ".venv/lib/python3.14/site-packages/altair/vegalite/v5/schema/_config.py", line 6491, in <module>
    class StepKwds(TypedDict, closed=True, total=False):  # type: ignore[call-arg]
    ...<21 lines>...
        __extra_items__: StepFor_T
TypeError: _TypedDictMeta.__new__() got an unexpected keyword argument 'closed'
```

**Comment by daizutabi** [comment]
I've looked into this issue and it seems there are two separate problems that prevent `altair` from working on Python 3.14.

1.  **Incorrect Version Check in Source Code:** The code incorrectly tries to use `typing.TypedDict` with new features on Python 3.14, but these features are only available from Python 3.15 onwards. This has already been fixed in PR #3877, but it is not yet in a released version.

2.  **Missing Dependency in `pyproject.toml`:** The `pyproject.toml` file for `altair` is missing `typing_extensions` as a dependency for Python 3.14 (`python_version<"3.14"` should be `python_version<"3.15"`). This is the cause of the `ModuleNotFoundError`.

For anyone who needs a workaround right now, you can use the `main` branch of `altair` and explicitly add `typing_extensions` to your `pyproject.toml`. Here is an example of a `pyproject.toml` that works on Python 3.14:

```toml
[project]
name = "my_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "altair @ git+https://github.com/vega/altair.git@main",
    "typing-extensions>=4.15.0",
]
```

I will open a pull request shortly to fix the missing dependency in the `pyproject.toml` file.
